# -*- coding: utf-8 -*-

import sys
import os
import subprocess

exit_code = subprocess.call(
    ['/usr/bin/python3', '-W', 'ignore', '/usr/local/lib/python3.12/dist-packages/nuitka/build/inline_copy/bin/scons.py', '-f', '/usr/local/lib/python3.12/dist-packages/nuitka/build/Backend.scons', '--jobs', '1', '--warn=no-deprecated', '--no-site-dir', '--debug=stacktrace', 'source_dir=.', 'nuitka_python=false', 'debug_mode=true', 'debugger_mode=false', 'python_debug=false', 'module_mode=true', 'full_compat=false', 'experimental=', 'trace_mode=false', 'file_reference_mode=runtime', 'module_count=2', 'debian_python=true', 'python_sysflag_utf8=true', 'result_exe=/code/module.cpython-312-x86_64-linux-gnu.so', 'nuitka_src=/usr/local/lib/python3.12/dist-packages/nuitka/build', 'python_version=3.12', 'python_prefix=/usr', 'debug_modes=debug_immortal', 'no_deployment=', 'show_scons=true', 'lto_mode=no', 'unstripped_mode=true', 'target_arch=x86_64'],
    env={'HOME': '/root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'DEBIAN_FRONTEND': 'noninteractive', 'PWD': '/code', 'SVACE_BUILD_DEBUG_LEVEL': '3', 'SVACE_BUILD_DEBUG_OUTPUT': '/code/.svace-dir/bitcode/build-debug.log', 'CCACHE_DISABLE': '1', 'MSBUILDDISABLENODEREUSE': '1', 'LIB_CONTEXT_VAL': '/opt/svace-3.4.240516-x64-linux:/code/.svace-dir:/code/.svace-dir/bitcode:off:/opt/svace-3.4.240516-x64-linux/scripts/build-capture/redirect.py::::::/opt/svace-3.4.240516-x64-linux/external-tools/x64-linux/jre17:/opt/svace-3.4.240516-x64-linux/share/java/tags-javac.jar:2048:2048:/opt/svace-3.4.240516-x64-linux/compilers/golangc-x64-linux:auto::/opt/svace-3.4.240516-x64-linux/prog/build-capture/dummy:/usr/local/sbin\\:/usr/local/bin\\:/usr/sbin\\:/usr/bin\\:/sbin\\:/bin:\\0:/opt/svace-3.4.240516-x64-linux/bin/../external-tools/x64-linux/python-3.8/bin/python3:/code/.svace-dir/bitcode/hash-serv-in.fifo::\\0:/opt/svace-3.4.240516-x64-linux/external-tools/x64-linux/dotnet/dotnet::357:none:', 'SVACE_CONTEXT_ENV': '1111001010011011001001001110111100000010', 'LD_PRELOAD': 'libsvace.so', 'LD_LIBRARY_PATH': '/opt/svace-3.4.240516-x64-linux/prog/build-capture/x86:/opt/svace-3.4.240516-x64-linux/prog/build-capture/x64:/opt/svace-3.4.240516-x64-linux/prog/build-capture/arm:/opt/svace-3.4.240516-x64-linux/prog/build-capture/aarch64', 'ALLOW_NINJA_ENV': '1', 'LC_CTYPE': 'C.UTF-8', 'NUITKA_SITE_FILENAME': '19:/usr/lib/python3.12/site.py', 'PYTHONHASHSEED': '0', 'NUITKA_PYTHON_EXE_PATH': '/usr/bin/python3', 'NUITKA_PACKAGE_DIR': '/usr/local/lib/python3.12/dist-packages/nuitka', '_NUITKA_BUILD_DEFINITIONS_CATALOG': '_NUITKA_BUILD_DEFINITIONS_CATALOG', 'NUITKA_QUIET': '0'},
    shell=False
)